apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  destination:
    namespace: db
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/your-org/infra
    targetRevision: HEAD
    path: db/mongodb
    helm:
      parameters:
        - name: auth.enabled
          value: "true"
        - name: auth.rootPassword
          value: yourMongoRootPwd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true