apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
#      targetPort: 443
#    - name: redis
#      port: 6379
#      targetPort: 6379
#    - name: mongo
#      port: 27017
#      targetPort: 27017
#    - name: mysql
#      port: 3306
#      targetPort: 3306